
// let var1 = document.getElementById('var1');
// let var2 = document.getElementById('var2');
// let var3 = document.getElementById('var3');
// let var4 = document.getElementById('var4');
// let var5 = document.getElementById('var5');

let varInput1 = document.getElementById('varInput1');
let varInput2 = document.getElementById('varInput2');
let varInput3 = document.getElementById('varInput3');
let varInput4 = document.getElementById('varInput4');
let varInput5 = document.getElementById('varInput5');
let textoClinico = document.getElementById('textoClinico');
let caseNumber = ''

const data = {
    '0': {
      fecha_presentacion_principal: 1692316800000,
      puesto_trabajo: 'MUCAMA',
      fecha_accidente: 1692316800000,
      ingreso_tardio: null,
      mecanismo: '92',
      rubro: 853,
      cantidad_siniestros: 1,
      uo_sede_ingreso: ' CALAMA',
      uo_servicio_ingreso: 'US_ATENCION_AMBULATORIA',
      uo_medica_ingreso: 'UM_ATENCION_PRIMARIA',
      id_uo_tratamiento_ingreso: 'CLMTCAPR',
      uo_tratamiento_ingreso: 'CONSULTA_AP',
      tipo_siniestro_origen: '2',
      ult_tipo_siniestro_primer_dia: '2',
      tipo_siniestro_actual: '2',
      tipo_siniestro_origen_desc: 'Trayecto',
      ult_tipo_siniestro_primer_dia_desc: 'Trayecto',
      tipo_siniestro_actual_desc: 'Trayecto',
      tipo_ley: '1',
      tipo_ley_desc: 'Ley 16.744',
      anteced: 'AL MOMENTO DEL ACCIDENTE ESTABA CAMINANDO DESDE SU DOMICILIO UBICADO EN',
      relato_admision: 'AL MOMENTO DEL ACCIDENTE ESTABA CAMINANDO DESDE SU DOMICILIO UBICADO EN CALLE FAUSTINO SARMIENTO HACIA SU TRABAJO EN HOTEL IBIS PARA DAR INICIO A SU JORNADA. LO QUE OCURRIO FUE QUE MIENTRAS IBA CAMINANDO AV PRATEN UN PASO PEATONAL UN CONDUCTOR NO LA VIO POR CULPA DEL SOL, ATROPELLANDOLA, PROVOCANDO QUE SALIERA PROYECTADA. EL ACCIDENTE OCURRIO CON UN CONDUCTOR, NO TIENE TESTIGOS DE SU ACCIDENTE, AVISO A LA EMPRESA, EL NOMBRE Y CARGO  DE LA PERSONA ES VERONICA ORTIZ, JEFATURA, FECHA Y HORA EN QUE AVISO A SU EMPRESA SOBRE EL ACCIDENTE: 18.08.2023 A LAS 07:45:00',
      cod_ubic_les: '900',
      parte_lesionada: 'Otras partes del cuerpo lesionadas',
      criterio_gravedad: '1',
      tiene_salud_mental: 0,
      tiene_fractura: 1,
      cantidad_diag_fractura: 2,
      fecha_primer_diag_fractura: 1692316800000,
      fecha_ultimo_diag_fractura: 1695254400000,
      cantidad_diagnosticos: 2,
      codigo_diagnostico_1: '8586',
      fecha_creacion_diag_1: 1692316800000,
      mediana_mono_diag_1: 73.4642857143,
      mediana_poli_diag_1: 140.2542372881,
      std_diag_1: 138.2309611572,
      prop_ctp_diag_1: 0.9766233766,
      q20_diag_1: 31,
      q80_diag_1: 147.4,
      lateralidad_diag_1: 'derecho',
      ubicacion_lesion_diag_1: 'extremidad inferior',
      cie10_diag_1: 'S824',
      bloque_general_diag_1: 'EXTREMIDAD INFERIOR',
      bloque_especifico_diag_1: 'FRACTURA PIERNA, INCLUSIVE EL TOBILLO',
      codigo_grupo_diag_1: 'S82',
      cie10_grupo_diag_1: 'S00_T99',
      cie10_macro_diag_1: 'S',
      codigo_diagnostico_2: 'A001',
      fecha_creacion_diag_2: 1692316800000,
      mediana_mono_diag_2: null,
      mediana_poli_diag_2: null,
      std_diag_2: null,
      prop_ctp_diag_2: null,
      q20_diag_2: null,
      q80_diag_2: null,
      lateralidad_diag_2: 'no especificada',
      ubicacion_lesion_diag_2: 'no_encontrado',
      cie10_diag_2: null,
      bloque_general_diag_2: null,
      bloque_especifico_diag_2: null,
      codigo_grupo_diag_2: null,
      cie10_grupo_diag_2: null,
      cie10_macro_diag_2: null,
      dia_semana_principal: 'Viernes',
      fecha_nacimiento_bp: 549590400000,
      sexo: 'femenino',
      dias_reposo_totales: 53,
      primer_fecha_inicio_reposo: 1692316800000,
      primer_fecha_indicacion_reposo: 1692316800000,
      dias_reposo_iniciales: 53,
      grado_total_incapacidad: null,
      fecha_resolucion: null,
      modalidad_incapacidad_desc: null,
      primera_terapia_fisica: null,
      primera_terapia_ocupacional: null,
      id_via_administracion: null,
      via_maxima: null,
      descripcion_formato: null,
      antibioticos: null,
      anticoagulantes_orales: null,
      hipoglicemiantes: null,
      tromboliticos: null,
      nivel_carga_laboral: 3,
      hospitalizado: null,
      anamnesis: 'DG: FRACTURA DIAFISARIA 1/3 PROXIMAL DE PERONE DERECHO.FECHA DEL ACCIDENTE: 18/08/23 DIAS DE EVOLUCION: 3 MEDICAMENTOS: ANALGESIA.PLAN: ORTOPEDICO/EN ESTUDIO. ENTERADO DEL CASO ADHERENCIA AL TRATAMIENTO, BUENA RESPUESTA A ANALG00c9SICOS, SIN RAM.PACIENTE ACUDE A CONTROL MEDICO, REIFEREDG: FRACTURA DIAFISARIA 1/3 PROXIMAL DE PERONE DERECHO.FECHA DEL ACCIDENTE: 18/08/23DIAS DE EVOLUCI00d3N: 6MEDICAMENTOS: ANALGESIA.PLAN: ORTOPEDICO/EN ESTUDIO.ENTERADO DEL CASOADHERENCIA AL TRATAMIENTO, BUENA RESPUESTA A ANALG00c9SICOS, SIN RAM.PACIENTE ACUDE A CONTROL MEDICO, REIFERE PERSISTENCIA DE DOLOR EN PIERNA DERECHA ENA 3/10, TOLERADO.DG: FRACTURA DIAFISARIA 1/3 PROXIMAL DE PERONE DERECHO.FECHA DEL ACCIDENTE: 18/08/23DIAS DE EVOLUCI00d3N: 6MEDICAMENTOS: ANALGESIA.PLAN: ORTOPEDICO/EN ESTUDIO.ENTERADO DEL CASO SE REGULARIZAN OM TMT.DG: FRACTURA DIAFISARIA 1/3 PROXIMAL DE PERONE DERECHO.FECHA DEL ACCIDENTE: 18/08/23DIAS DE EVOLUCI00d3N: 6MEDICAMENTOS: ANALGESIA.PLAN: ORTOPEDICO/EN ESTUDIO.ENTERADO DEL CASOPACIENTE REFIERE MANTENER DOLOR EVA 3/10 LOGRA APOYO PERO AL FLEXIONAR GENERA DOLORAM: (-)FCOS: (-)ANT. QX: CESAREA.ALERGIAS: (-)OCUPACI00d3N: MUCAMA HORARIO: 6X1 ROTATIVO.EMPRESA: HOTEL IBIS.CUADRO OCURRE EL DIA DE HOY A LAS 7:30AM (4H DE EVOLUCION AL INGRESO)EN TRAYECTO A JORNADA LABORAL.PACIENTE REFIERE QUE MIENTRAS SE TRASLADABA A SU TRABAJO EN SCOOTER, MIENTRAS ATRAVIESA PASO DE CEBRA EN AV. ARTURO PRATT, ES ALCANZADA POR AUTOMOVIL QUE LA ARROLLA, CAYENDO EN ACERA SOBRE SU COSTADO DERECHO. ACTUALMENTE PRESENTA DOLOR EN REGION OCCIPITAL, HOMBRO, HEMITORAX Y PIERNA DERECHA. ASI MISMO REFIERE PERDIDA DE CONSCIENCIA (NO OBJETIVA TIEMPO) <1MIN. NIEGA MAREOS, NAUSEAS, VOMITOS, DOLOR ABDOMINAL, DISNEA.',
      examen_fisico: 'PACIENTE EN CONDICIONES CLINICAS ESTABLES. AFEBRIL, HIDRATADA, EUPNEICA.CLOTE. CP: MP+, SRA, RR2T S/S.ABD: BLANDO, DEPRESIBLE, NO DOLOROSO A LA PALPACION, SIN SIGNOS DE IRRITACION PERITONEAL.EXT: DOLOR A LA PALPACION DE HOMBRO DERECHO, LIMITACION FUNCIONAL POR DOLOR.DOLOR A LA PALPACION DE CARA ANTEROLATERAL DE PIERNA DERECHA 1/3 PROXIMAL, AVO ++/+++, SIN EQUIMOSIS NI DEFORMIDAD.ROM DE PIE Y TOBILLO COMPLETOS. NV CONSERVADO. PACIENTE EN CONDICIONES CLINICAS ESTABLES.MARCHA ASISTIDA POR BASTONES.AFEBRIL, HIDRATADA, EUPNEICA.CLOTE. CP: MP+, SRA, RR2T S/S.ABD: BLANDO, DEPRESIBLE, NO DOLOROSO A LA PALPACION, SIN SIGNOS DE IRRITACION PERITONEAL.EXT: INMOVILIZACION INGUINOPEDICA, EDEMA GLOBAL LEVE, SIN HERIDAS, APARATO EXTENSOR COMPETENTE, ROM ACTIVOS Y PASIVOS COMPLETOS, DOLOR EN RODILLA Y LARA LATERAL DE PIERNA. BIPEDESTACION CON EQUILIBRIO. NO LOGRA APOYO MONOPODAL. FM Y NV CONSERVADO.REALIZADO POR TMT.PACIENTE EN CONDICIONES CLINICAS ESTABLES.MARCHA ASISTIDA POR BASTONES.AFEBRIL, HIDRATADA, EUPNEICA.CLOTE. CP: MP+, SRA, RR2T S/S.ABD: BLANDO, DEPRESIBLE, NO DOLOROSO A LA PALPACION, SIN SIGNOS DE IRRITACION PERITONEAL.EXT: INMOVILIZACION INGUINOPEDICA, EDEMA GLOBAL LEVE, SIN HERIDAS, APARATO EXTENSOR COMPETENTE, ROM ACTIVOS Y PASIVOSCOMPLETOS, DOLOR EN RODILLA Y LARA LATERAL DE PIERNA. BIPEDESTACION CON EQUILIBRIO. NO LOGRA APOYO MONOPODAL. FM Y NVCONSERVADO.PACIENTE EN CONDICIONES CLINICAS ESTABLES.AFEBRIL, HIDRATADA, EUPNEICA.INGRESA EN CAMILLA DESDE AMBULANCIA.DOLOR Y AVO EN REGION OCCIPITAL SIN CREPITACION NI HERIDA.COLUMNA CERVICAL CON DOLOR A LA PALPACION POSTERIOR.CLOTE. CP: MP+, SRA, RR2T S/S.ABD: BLANDO, DEPRESIBLE, NO DOLOROSO A LA PALPACION, SIN SIGNOS DE IRRITACION PERITONEAL.EXT: DOLOR A LA PALPACION DE HOMBRO DERECHO, LIMITACION FUNCIONAL POR DOLOR.DOLOR A LA PALPACION DE CARA ANTEROLATERAL DE PIERNA DERECHA 1/3 PROXIMAL, AVO ++/+++, SIN EQUIMOSIS NI DEFORMIDAD.ROM DE PIE Y TOBILLO COMPLETOS. NV CONSERVADO.',
      indicacion_medico: 'Reposo si, con incapacidad laboral temporalTransporte si, Llevar - Traer con pierna extendida , hasta el pr00f3ximo contr***ORDENES CLINICAS GENERADAS***Reposo si, con incapacidad laboral temporalTransporte: No.***ORDENES CLINICAS GENERADAS*** -.- CELECOXIB 200 MG (A), ORAL, 200MG, C/24 HRS AM ,por 10  d00edas [ 0  ]Reposo si, con incapacidad laboral temporalTransporte si, Llevar - Traer en Automovil , hasta el pr00f3ximo control200b***ORDENES CLINICAS GENERADAS***ATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAATENCION KINESIOLOGICA INTEGRAL AMBULATO | FRACTURA PERONE, DIAFISIARIA CERRADAEVALUACION KINESIOLOGICA INTEGRALEVALUACION KINESIOLOGICA INTEGRAL -.- CELECOXIB 200 MG (A), ORAL, 200MG, C/24 HRS AM ,por 10  d00edas [ 0  ]Reposo si, con incapacidad laboral temporalTransporte si, Llevar-Traer en Furg00f3n , hasta el pr00f3ximo control200b***ORDENES CLINICAS GENERADAS*** -.- CELECOXIB 200 MG (A), ORAL, 200MG, C/24 HRS AM ,por 15  d00edas [ 0  ]Reposo si, con incapacidad laboral temporalTransporte si, Llevar - Traer en Automovil , hasta el pr00f3ximo control200b***ORDENES CLINICAS GENERADAS*** -.- CELECOXIB 200 MG (A), ORAL, 200MG, C/12 HRS ,por 10  d00edas [ 0  ]TRAMADOL 37.5 MG - PARACETAMOL 325 MG (A), ORAL, 1CMP, C/8 HRS ,por 10  d00edas [ 0  ]DICLOFENACO 1% / 30 GR (A)., TOPICA, 35APL, SEGUN NECESIDAD ,por 1  d00edas [ 0  ]CICLOBENZAPRINA 10 MG (A), ORAL, 10MG, C/24 HRS PM ,por 58  d00edas [ 0  ]',
      cantidad_prestaciones_eco: null,
      primera_prestaciones_eco: null,
      ultima_prestaciones_eco: null,
      dif_entre_eco: null,
      dif_a_primer_eco: null,
      prop_eco_por_dias: null,
      cantidad_prestaciones_rm: null,
      primera_prestaciones_rm: null,
      ultima_prestaciones_rm: null,
      dif_entre_rm: null,
      dif_a_primer_rm: null,
      prop_rm_por_dias: null,
      cantidad_prestaciones_rx: 8,
      primera_prestaciones_rx: 1692316800000,
      ultima_prestaciones_rx: 1695340800000,
      dif_entre_rx: 36,
      dif_a_primer_rx: 0,
      prop_rx_por_dias: 1.2285714149,
      cantidad_prestaciones_tac: 1,
      primera_prestaciones_tac: 1692316800000,
      ultima_prestaciones_tac: 1692316800000,
      dif_entre_tac: 1,
      dif_a_primer_tac: 0,
      prop_tac_por_dias: null,
      cantidad_prestaciones_tmt: 5,
      primera_prestaciones_tmt: 1692316800000,
      ultima_prestaciones_tmt: 1695254400000,
      dif_entre_tmt: 35,
      dif_a_primer_tmt: 0,
      prop_tmt_por_dias: 1.1470588446,
      cantidad_ordenes_cirugia: null,
      primera_orden_cirugia: null,
      ultima_orden_cirugia: null,
      dif_entre_cirugia: null,
      dif_a_primer_cirugia: null,
      prop_cirugia_por_dias: null,
      cantidad_ordenes_tf: 2,
      primera_orden_tf: 1695254400000,
      ultima_orden_tf: 1695254400000,
      dif_entre_tf: 1,
      dif_a_primer_tf: 0,
      prop_tf_por_dias: null,
      dia_de_presentacion: 4,
      mes_de_presentacion: 8,
      es_hombre: 0,
      edad_presentacion: 36.2115580744,
      tuvo_tf: 0,
      tuvo_to: 0,
      dif_dias_a_tf: null,
      dif_dias_a_to: null,
      dif_dias_a_accidente: 0,
      dif_dias_a_diag_1: 0,
      fecha_carga: '2023-10-09',
      hora_carga: '15:40',
      Max_protocolo: 120
    },
    '1': {
      puesto_trabajo: 'carniceria',
      fecha_accidente: 1692316800000,
      ingreso_tardio: null,
      mecanismo: '92',
      rubro: 612,
      cantidad_siniestros: 1,
      uo_sede_ingreso: ' TEMUCO',
      uo_servicio_ingreso: 'US_ATENCION_HOSPITALIZACION',
      uo_medica_ingreso: 'OTRA',
      id_uo_tratamiento_ingreso: 'TEMTHPEX',
      uo_tratamiento_ingreso: 'OTRA',
      tipo_siniestro_origen: '1',
      ult_tipo_siniestro_primer_dia: '1',
      tipo_siniestro_actual: '1',
      tipo_siniestro_origen_desc: 'Trabajo',
      ult_tipo_siniestro_primer_dia_desc: 'Trabajo',
      tipo_siniestro_actual_desc: 'Trabajo',
      tipo_ley: '1',
      tipo_ley_desc: 'Ley 16.744',
      anteced: 'AL MOMENTO DEL ACCIDENTE ESTABA CORTANDO CARNE CON MAQUINA DE CORTA HUESO',
      relato_admision: 'AL MOMENTO DEL ACCIDENTE ESTABA CORTANDO CARNE CON MAQUINA DE CORTA HUESO. LO QUE OCURRIO FUE QUE SE PASA A LLEVAR DEDO MANO IZQ.. EL ACCIDENTE OCURRIO CON HERIDA CORTANTE., NO TIENE TESTIGOS DE SU ACCIDENTE, AVISO A LA EMPRESA, FECHA Y HORA EN QUE AVISO A SU EMPRESA SOBRE EL ACCIDENTE: 18.08.2023 A LAS 16:31:00',
      cod_ubic_les: '900',
      parte_lesionada: 'Otras partes del cuerpo lesionadas',
      criterio_gravedad: '1',
      tiene_salud_mental: 0,
      tiene_fractura: 0,
      cantidad_diag_fractura: null,
      fecha_primer_diag_fractura: null,
      fecha_ultimo_diag_fractura: null,
      cantidad_diagnosticos: 1,
      codigo_diagnostico_1: '8491',
      fecha_creacion_diag_1: 1692316800000,
      mediana_mono_diag_1: 143.46875,
      mediana_poli_diag_1: 227.1578947368,
      std_diag_1: 255.9323903692,
      prop_ctp_diag_1: 0.9319371728,
      q20_diag_1: 47.2,
      q80_diag_1: 238.6,
      lateralidad_diag_1: 'izquierda',
      ubicacion_lesion_diag_1: 'extremidad superior',
      cie10_diag_1: 'S680',
      bloque_general_diag_1: 'EXTREMIDAD SUPERIOR',
      bloque_especifico_diag_1: 'AMPUTACION TRAUMATICA DE LA MUNECA Y DE LA MANO',
      codigo_grupo_diag_1: 'S68',
      cie10_grupo_diag_1: 'S00_T99',
      cie10_macro_diag_1: 'S',
      codigo_diagnostico_2: null,
      fecha_creacion_diag_2: null,
      mediana_mono_diag_2: null,
      mediana_poli_diag_2: null,
      std_diag_2: null,
      prop_ctp_diag_2: null,
      q20_diag_2: null,
      q80_diag_2: null,
      lateralidad_diag_2: null,
      ubicacion_lesion_diag_2: null,
      cie10_diag_2: null,
      bloque_general_diag_2: null,
      bloque_especifico_diag_2: null,
      codigo_grupo_diag_2: null,
      cie10_grupo_diag_2: null,
      cie10_macro_diag_2: null,
      dia_semana_principal: 'Viernes',
      fecha_nacimiento_bp: 857433600000,
      sexo: 'masculino',
      dias_reposo_totales: 53,
      primer_fecha_inicio_reposo: 1692316800000,
      primer_fecha_indicacion_reposo: 1692316800000,
      dias_reposo_iniciales: 53,
      grado_total_incapacidad: null,
      fecha_resolucion: null,
      modalidad_incapacidad_desc: null,
      primera_terapia_fisica: null,
      primera_terapia_ocupacional: null,
      id_via_administracion: null,
      via_maxima: null,
      descripcion_formato: null,
      antibioticos: null,
      anticoagulantes_orales: null,
      hipoglicemiantes: null,
      tromboliticos: null,
      nivel_carga_laboral: null,
      hospitalizado: null,
      anamnesis: 'PACIENTE CON ANTECEDENTE DE ENFERMEDAD DE VON WILLENBRAND, SIN ALERGIASSUFRE AMPUTACI00d3N PARCIAL DE PUNTA PULGAR IZQUIERDO HACE 1 SEMANA.TIENE CONTROL PROXIMA SEMANA CON DR TROLL QUIEN LE HIZO UN VENDAJE SEMIOCLUSIVO. TOMANDO PARACETAMOL, CON DOLOR LEVE, SIN NECESIDAD DE MAYOR ANALGESIA.VIENE A ACHS PARA CAMBIO DE PARCHE, QUE SE LE HA DETERIORADO. SIN OTRAS MOLESTIASPcte de PerquencoAM: Enf Von WillebrandAlergias: AASCarniceroAcc. 18-08-23 (4 sem)Amputaci00f3n traum00e1tica punta D1 izq (Allen 1)Tto: Aseo + VSODada condici00f3n de coagulopat00eda, se hospitaliza para observaci00f3n 1 dia... sin complicaciones.61/2 SEM DE EVREFIERE ESTAR CON TEMOR AL REINTEGRO LUEGO DEL ACCIDENTE, CON LABILIDAD EMOCIONALPcte de PerquencoAM: Enf Von WillebrandAlergias: AASCarniceroAcc. 18-08-23 (4 sem)Amputaci00f3n traum00e1tica punta D1 izq (Allen 1)Tto: Aseo + VSODada condici00f3n de coagulopat00eda, se hospitaliza para observaci00f3n 1 dia... sin complicaciones.AM: Enf Von Willebrand Alergias: AASCarniceroAcc. 18-08-23 (2 sem)Amputaci00f3n traum00e1tica punta D1 izq (Allen 1)Tto: Aseo + VSODada condici00f3n de coagulopat00eda, se hospitaliza para observaci00f3n 1 dia... sin complicaciones.AM: ENFERMEDAD DE V. WILLEBRANDFCOS: (-)ANT. QX: (-)ALERGIAS: AASW:  tCARNICERODOMINANCIA: DIESTROHOY A LAS 16.30 EN SU TRABAJO ESTABA CORTANDO CARNE CON SIERRA EL00c9CTRICA Y SE REBANA PUNTA DEL DEDO PULGAR IZQUIERDO, EVOLUCIONA CON SANGRADO ABUNDANTE Y DOLOR EVA 7/10. VAT',
      examen_fisico: 'PULGAR IZQUIERDO, SE OBSERVA PARCHE CON LEVE SUCIEDAD, SE RETIRA POR PARTES, SE RENUEVA PARCHE SIN RETIRAR SEMIOCLUSIVO. SIN OTROS HALLAZGOS.PULGAR IZQ CON CICATRIZACION 95%. CON COSTRA EN VERTICE HIPERSENSIBLE PULPEJO DE PULGAR LIMITADA LA FLEXION AUN Y CON POCA POTENCIA Se retira VSO Punta de D1 izq con tej. granulatorio ++ con relleno casi completo de vertice. Rigidez ++ de pulgar. Aposito externo limpio Tegaderm in situ Resto de mano con xerosis SE EXAMINA A PACIENTE YA ESTANDO EN BOX DE PROCEDIMIENTOS, SE RETIRA VENDAJE. SANGRADO ABUNDANTE ACTIVO QUE IMPIDE VISUALIZAR LESION, SE APLICA TORNIQUETE, SE OBSERVA AMPUTACION PARCIAL DE FALANGE DISTAL PULGAR IZQUIERDO CON COMPROMISO DE LA U00d1A, IMPRESIONA ALLEN 1-2. NV CONSERVADO. ROM CONSERVADOS. ',
      indicacion_medico: 'Reposo si, con incapacidad laboral temporalTransporte: No.***ORDENES CLINICAS GENERADAS***CURACION INTERMEDIAReposo si, con incapacidad laboral temporalTransporte: No.***ORDENES CLINICAS GENERADAS***EVALUACION KINESIOLOGICA INTEGRALEVALUACION KINESIOLOGICA INTEGRALEVALUACION KINESIOLOGICA INTEGRALReposo si, con incapacidad laboral temporalTransporte: No.***ORDENES CLINICAS GENERADAS***CURACION AVANZADA | post kineEVALUACION KINESIOLOGICA INTEGRALEVALUACION KINESIOLOGICA INTEGRAL -.- ACIDO ASCORBICO 500 MG (A), ORAL, 500MG, C/24 HRS AM ,por 14  d00edas [ 0  ]PARACETAMOL 500 MG (A), ORAL, 1000MG, C/12 HRS ,por 14  d00edas [ 0  ]CELECOXIB 200 MG (A), ORAL, 200MG, SEGUN NECESIDAD ,por 7  d00edas [ 0  ]Reposo si, con incapacidad laboral temporalTransporte: No.***ORDENES CLINICAS GENERADAS***CURACION SIMPLE | Solo recambio de aposito externo, no tegadermCURACION SIMPLE -.- PARACETAMOL 500 MG (A), ORAL, 1000MG, C/8 HRS ,por 14  d00edas [ 0  ]CELECOXIB 200 MG (A), ORAL, 200MG, SEGUN NECESIDAD ,por 10  d00edas [ 0  ]EUCERIN PH-5 LOCION 250 ML, TOPICA, 20APL, SEGUN NECESIDAD ,por 1  d00edas [ 0  ]CREMA MULTIPROP00d3SITO MANOS (A), TOPICA, 20APL, SEGUN NECESIDAD ,por 1  d00edas [ 0  ]Reposo si, con incapacidad laboral temporalTransporte: No.***ORDENES CLINICAS GENERADAS***Reposo si, con incapacidad laboral temporalTransporte si, Llevar en Furg00f3n***ORDENES CLINICAS GENERADAS***HOSPITALIZACION EXTERNA COMUNHOSPITALIZACION EXTERNA COMUNHOSPITALIZACION EXTERNA COMUNHOSPITALIZACION EXTERNA COMUN',
      cantidad_prestaciones_eco: null,
      primera_prestaciones_eco: null,
      ultima_prestaciones_eco: null,
      dif_entre_eco: null,
      dif_a_primer_eco: null,
      prop_eco_por_dias: null,
      cantidad_prestaciones_rm: null,
      primera_prestaciones_rm: null,
      ultima_prestaciones_rm: null,
      dif_entre_rm: null,
      dif_a_primer_rm: null,
      prop_rm_por_dias: null,
      cantidad_prestaciones_rx: 3,
      primera_prestaciones_rx: 1692316800000,
      ultima_prestaciones_rx: 1692316800000,
      dif_entre_rx: 1,
      dif_a_primer_rx: 0,
      prop_rx_por_dias: null,
      cantidad_prestaciones_tac: null,
      primera_prestaciones_tac: null,
      ultima_prestaciones_tac: null,
      dif_entre_tac: null,
      dif_a_primer_tac: null,
      prop_tac_por_dias: null,
      cantidad_prestaciones_tmt: 7,
      primera_prestaciones_tmt: 1692316800000,
      ultima_prestaciones_tmt: 1697068800000,
      dif_entre_tmt: 56,
      dif_a_primer_tmt: 0,
      prop_tmt_por_dias: 1.1272727251,
      cantidad_ordenes_cirugia: null,
      primera_orden_cirugia: null,
      ultima_orden_cirugia: null,
      dif_entre_cirugia: null,
      dif_a_primer_cirugia: null,
      prop_cirugia_por_dias: null,
      cantidad_ordenes_tf: 2,
      primera_orden_tf: 1694649600000,
      ultima_orden_tf: 1696291200000,
      dif_entre_tf: 20,
      dif_a_primer_tf: -19,
      prop_tf_por_dias: 1.105263114,
      dia_de_presentacion: 4,
      mes_de_presentacion: 8,
      es_hombre: 1,
      edad_presentacion: 26.4563954085,
      tuvo_tf: 0,
      tuvo_to: 0,
      dif_dias_a_tf: null,
      dif_dias_a_to: null,
      dif_dias_a_accidente: 0,
      dif_dias_a_diag_1: 0,
      fecha_carga: '2023-10-09',
      hora_carga: '15:40',
      Max_protocolo: 121
    },
    '2': {
      puesto_trabajo: 'mercaderista',
      fecha_accidente: 1693180800000,
      ingreso_tardio: null,
      mecanismo: '92',
      rubro: 640,
      cantidad_siniestros: 1,
      uo_sede_ingreso: ' CONCEPCION',
      uo_servicio_ingreso: 'US_ATENCION_AMBULATORIA',
      uo_medica_ingreso: 'UM_ATENCION_PRIMARIA',
      id_uo_tratamiento_ingreso: 'CNCTCAPR',
      uo_tratamiento_ingreso: 'CONSULTA_AP',
      tipo_siniestro_origen: '2',
      ult_tipo_siniestro_primer_dia: '2',
      tipo_siniestro_actual: '2',
      tipo_siniestro_origen_desc: 'Trayecto',
      ult_tipo_siniestro_primer_dia_desc: 'Trayecto',
      tipo_siniestro_actual_desc: 'Trayecto',
      tipo_ley: '1',
      tipo_ley_desc: 'Ley 16.744',
      anteced: 'AL MOMENTO DEL ACCIDENTE ESTABA EN CALLE LOS CHIFLONES ALTURA DE MANUEL MONTT CON DIRECCION A  SU TRABAJO UBICADO EN LIDER CORONEL',
      relato_admision: 'AL MOMENTO DEL ACCIDENTE ESTABA EN CALLE LOS CHIFLONES ALTURA DE MANUEL MONTT CON DIRECCION A  SU TRABAJO UBICADO EN LIDER CORONEL. LO QUE OCURRIO FUE QUE AL TROPEZAR CON DESNIVEL DE LA VEREDA CAE GOLPEANDO BRAZO DERECHO. EL ACCIDENTE OCURRIO CON CAIDA POR DESNIVEL DEL SUELO ., NO TIENE TESTIGOS DE SU ACCIDENTE, AVISO A LA EMPRESA, EL NOMBRE Y CARGO  DE LA PERSONA ES RODRIGO, SUPERVISOR, FECHA Y HORA EN QUE AVISO A SU EMPRESA SOBRE EL ACCIDENTE: 28.08.2023 A LAS 07:15:00',
      cod_ubic_les: '900',
      parte_lesionada: 'Otras partes del cuerpo lesionadas',
      criterio_gravedad: '1',
      tiene_salud_mental: 0,
      tiene_fractura: 1,
      cantidad_diag_fractura: 1,
      fecha_primer_diag_fractura: 1693180800000,
      fecha_ultimo_diag_fractura: 1693180800000,
      cantidad_diagnosticos: 3,
      codigo_diagnostico_1: '8224',
      fecha_creacion_diag_1: 1693180800000,
      mediana_mono_diag_1: 106.4018691589,
      mediana_poli_diag_1: 168.296803653,
      std_diag_1: 178.5526744065,
      prop_ctp_diag_1: 0.9673590504,
      q20_diag_1: 39,
      q80_diag_1: 196.8,
      lateralidad_diag_1: 'no especificada',
      ubicacion_lesion_diag_1: 'extremidad superior',
      cie10_diag_1: 'S422',
      bloque_general_diag_1: 'EXTREMIDAD SUPERIOR',
      bloque_especifico_diag_1: 'FRACTURA DEL HOMBRO Y DEL BRAZO',
      codigo_grupo_diag_1: 'S42',
      cie10_grupo_diag_1: 'S00_T99',
      cie10_macro_diag_1: 'S',
      codigo_diagnostico_2: '8199',
      fecha_creacion_diag_2: 1693180800000,
      mediana_mono_diag_2: 21.3989361702,
      mediana_poli_diag_2: 41.2141230068,
      std_diag_2: 118.926377254,
      prop_ctp_diag_2: 0.9752973468,
      q20_diag_2: 5,
      q80_diag_2: 33,
      lateralidad_diag_2: 'no especificada',
      ubicacion_lesion_diag_2: 'extremidad superior',
      cie10_diag_2: 'S400',
      bloque_general_diag_2: 'EXTREMIDAD SUPERIOR',
      bloque_especifico_diag_2: 'TRAUMATISMO SUPERFICIAL DEL HOMBRO Y DEL BRAZO',
      codigo_grupo_diag_2: 'S40',
      cie10_grupo_diag_2: 'S00_T99',
      cie10_macro_diag_2: 'S',
      dia_semana_principal: 'Lunes',
      fecha_nacimiento_bp: 48124800000,
      sexo: 'femenino',
      dias_reposo_totales: 43,
      primer_fecha_inicio_reposo: 1693180800000,
      primer_fecha_indicacion_reposo: 1693180800000,
      dias_reposo_iniciales: 43,
      grado_total_incapacidad: null,
      fecha_resolucion: null,
      modalidad_incapacidad_desc: null,
      primera_terapia_fisica: null,
      primera_terapia_ocupacional: null,
      id_via_administracion: null,
      via_maxima: null,
      descripcion_formato: null,
      antibioticos: null,
      anticoagulantes_orales: null,
      hipoglicemiantes: null,
      tromboliticos: null,
      nivel_carga_laboral: null,
      hospitalizado: null,
      anamnesis: '5 1/2 semanas de evolucion fractura no desplazada en 3 partes del humero proximal derecho. rx de hoy con fractura consolidada sin desplazamiento.AM NOFX NO RAM NOOCUPACION: MERCADERISTAHOY EN LA MA00d1ANA CAMINO AL TRABAJO. DEBIDO A SUPERFICIE RESBALOSA POR LLUVIA, PIERDE EQUILIBRIO , CAE HACIA LADO DERECHO, AL TRATAR DE APOYARSE CON BRAZO EXTENDIDO REALIZANDO EXTENSION LEVE-MODERADA DE HOMBRO, SE APOYA Y EVOLUCIONA CON INTENSO DOLOR EN REGION LATERAL DE HOMBRO DERECHO. ADEMAS SE GOLPEA DE FORMA CONTUSA EN REGION COSTAL DERECHA Y CODO DERECHO.INGRESA CON INTENSO DOLOR, SIGNO DE LA CARTERA. A LA EVALUACION CLINICA INICIAL LLORA. SOLICITO MULTIPLES IMAGENES. PROBABLE LESION OSEA EN HUMERO PROXIMAL. ****Reev:TAC TORAX S/CEn este examen no hay visibilidad adecuada de los humeros .No hay otras lesiones en el esqueleto tor00e1cico visible .Discretas alteraciones basales, especialmente izquierda de aspecto residual inespec00edfica.TAC HOMBRO DERECHO:Fractura impactada del cuello quir00fargico del h00famero con extensi00f3n al troquiter y al troqu00edn.se presenta caso a TMT de turno, Dr. Barrientos. fractura no desplazada, se sugiere inmovilizador de hombro y control TMT diferido.16 dias de evolucion fractura tres partes no desplazada del humero proximal derecho. De mnanejo ortop00e9dico.rmercaderista. Coronel. Atorvastatina diestra. No fuma.rcae de nivel en v00eda publica con impacto en hombro derecho. ra y TAC confirman fractura del humero proximal y descartan lesiones tor00e1cicas.PACIENTE CONOCIDADG: - FX HUMERO - CONTUSION DE TORAXPACIENTE EN TRATAMIENTO POR TMT POR FX HUMERO PROXIMAL. EN INGRESO KNT INDICA PARESTESIA ,Y PERDIDA DE FUERZA EN MU00d1ECA Y MANO (3ER, 4TO Y 5TO DEDO). KNT SOLICITA EVALUACION MEDICA. LLAMA LA ATENCION QUE PACIENTE NO LOGRA COMPLETA PRONOSUPINACION.ADEMAS, LIMITACION EN RANGO ARTICULAR DE MU00d1ECA POR DOLOR, QUE NO IMPRESIONA FX, EN DORSO . SOLICITO RX. RX CODO Y MU00d1ECA NO IMPRESIONA FX. SOLICITO ECOTOMOGRAFIA DE CODO Y MU00d1ECA POR SOSPECHA DE LESION NEUROPATICA. JUNTO CON EMG DE EESS. CONTROL CON RESULTADO.MANTENER TTO POR ESPECIALISTA.',
      examen_fisico: 'algo aprehensiva, pero con explicaciones adecuadas se relaja y comprende. debe abandonar inmovilizador de inmediato e iniciar TF. sin complicacion neurovascular ni osteoarticular. Solo regidez propia de la lesion y de la inmovilizacion prolongada y aprehension logica. IMPOTENCIA FUCIONALDOLOR INTENSO CON LIMITACION DE RANGO ARTICULAR DOLOR 10/10 FUERZZA M4 DISTAL. SENSIBILIDAD CONSERVADA PERFUSION CONSERVADA.DOLOR INTENSO A LA PALPACION CARA LATERAL DE HOMBRO.SIN SIGNO DE LA TECLA. SIN SIGNOS DE LA CHARRETERA. DERIVO.dolor hombro derecho. se indican ejercicios de mano-mu00f1eca-codo 2 veces al d00eda con retiro de inmovilizador.rse explican plazos.rPARESTESIA 3ER 4TO QUINTO DEDO MANO DERECHAAVO DIFUSOFUERZA M5 DEBIL .ROM PASIVO CONSERVADO DOLOR 8/10. ACTIVO LIMITADO POR DOLOR. LOCALIZADO EN DORSO DE MU00d1ECA. CODO CON PRONOSUPINACION LIMITADA POR DOLOR. ',
      indicacion_medico: '- reposor- TFr- trasladosr- suspender hoy inmovilizador de hombror- control 4 semanasReposo si, con incapacidad laboral temporalTransporte si, Llevar-Traer en Furg00f3n , hasta el pr00f3ximo control200b***ORDENES CLINICAS GENERADAS*** -.- CELECOXIB 200 MG (A), ORAL, 200MG, C/24 HRS AM ,por 10  d00edas [ 0  ]TRAMADOL 37.5 MG - PARACETAMOL 325 MG (A), ORAL, 1CMP, C/8 HRS ,por 10  d00edas [ 0  ]PREGABALINA 75 MG (A), ORAL, 75MG, C/24 HRS PM ,por 10  d00edas [ 0  ]- reposor- trasladosr- inmovilizador permanenter- ejercicios en casa con retiro de inmovilizador 2 veces al diar- control con rx en 2 semanasReposo si, con incapacidad laboral temporalTransporte si, Llevar-Traer en Furg00f3n , hasta el pr00f3ximo control200b***ORDENES CLINICAS GENERADAS***ECOTOMOGRAFIA DE CODO | Lado derecho | EXTREMIDAD SUPERIOR DERECHA. OBS LESION NEUROPATICECOTOMOGRAFIA DE MU00d1ECA | Lado derecho | EXTREMIDAD SUPERIOR DERECHA. OBS LESION NEUROPATICELECTROMIOGRAFIAS CUALQUIER REGION | Lado derecho | EXTREMIDAD SUPERIOR DERECHA. OBS LESION NEUROPATICVELOCIDAD DE CONDUCCION (INCLUYE REFLEJO | Lado derecho | EXTREMIDAD SUPERIOR DERECHA. OBS LESION NEUROPATICEVALUACION KINESIOLOGICA INTEGRALEVALUACION KINESIOLOGICA INTEGRAL',
      cantidad_prestaciones_eco: 2,
      primera_prestaciones_eco: 1696550400000,
      ultima_prestaciones_eco: 1696550400000,
      dif_entre_eco: 1,
      dif_a_primer_eco: 39,
      prop_eco_por_dias: null,
      cantidad_prestaciones_rm: null,
      primera_prestaciones_rm: null,
      ultima_prestaciones_rm: null,
      dif_entre_rm: null,
      dif_a_primer_rm: null,
      prop_rm_por_dias: null,
      cantidad_prestaciones_rx: 8,
      primera_prestaciones_rx: 1693180800000,
      ultima_prestaciones_rx: 1696550400000,
      dif_entre_rx: 40,
      dif_a_primer_rx: 0,
      prop_rx_por_dias: 1.2051281929,
      cantidad_prestaciones_tac: 2,
      primera_prestaciones_tac: 1693180800000,
      ultima_prestaciones_tac: 1693180800000,
      dif_entre_tac: 1,
      dif_a_primer_tac: 0,
      prop_tac_por_dias: null,
      cantidad_prestaciones_tmt: 2,
      primera_prestaciones_tmt: 1693180800000,
      ultima_prestaciones_tmt: 1699401600000,
      dif_entre_tmt: 73,
      dif_a_primer_tmt: 0,
      prop_tmt_por_dias: 1.027777791,
      cantidad_ordenes_cirugia: null,
      primera_orden_cirugia: null,
      ultima_orden_cirugia: null,
      dif_entre_cirugia: null,
      dif_a_primer_cirugia: null,
      prop_cirugia_por_dias: null,
      cantidad_ordenes_tf: 2,
      primera_orden_tf: 1696550400000,
      ultima_orden_tf: 1696550400000,
      dif_entre_tf: 1,
      dif_a_primer_tf: 0,
      prop_tf_por_dias: null,
      dia_de_presentacion: 0,
      mes_de_presentacion: 8,
      es_hombre: 0,
      edad_presentacion: 52.1297494131,
      tuvo_tf: 0,
      tuvo_to: 0,
      dif_dias_a_tf: null,
      dif_dias_a_to: null,
      dif_dias_a_accidente: 0,
      dif_dias_a_diag_1: 0,
      fecha_carga: '2023-10-09',
      hora_carga: '15:40',
      Max_protocolo: 121
    },
    '3': {
      puesto_trabajo: 'EDUCADORA DE PARVULO',
      fecha_accidente: null,
      ingreso_tardio: null,
      mecanismo: null,
      rubro: 821,
      cantidad_siniestros: 1,
      uo_sede_ingreso: ' SAN FERNANDO',
      uo_servicio_ingreso: 'US_ATENCION_AMBULATORIA',
      uo_medica_ingreso: 'UM_ATENCION_PRIMARIA',
      id_uo_tratamiento_ingreso: 'FERTCAPR',
      uo_tratamiento_ingreso: 'CONSULTA_AP',
      tipo_siniestro_origen: '3',
      ult_tipo_siniestro_primer_dia: '3',
      tipo_siniestro_actual: '3',
      tipo_siniestro_origen_desc: 'Enfermedad Profesional',
      ult_tipo_siniestro_primer_dia_desc: 'Enfermedad Profesional',
      tipo_siniestro_actual_desc: 'Enfermedad Profesional',
      tipo_ley: '2',
      tipo_ley_desc: 'Ley 19.394',
      anteced: 'CRISIS DE PANICO, ASELERACION CARDIACA, CAIDA DE PELO, URTICARIA,',
      relato_admision: 'CRISIS DE PANICO, ASELERACION CARDIACA, CAIDA DE PELO, URTICARIA, ANGUSTIA, INSOMNIO, PESADILLAS, LLANTO, DEBILIDAD EMOCIONAL, TODO ESTO A RAIZ DE SOBRECARGA LABORAL',
      cod_ubic_les: '900',
      parte_lesionada: 'Otras partes del cuerpo lesionadas',
      criterio_gravedad: null,
      tiene_salud_mental: 1,
      tiene_fractura: 0,
      cantidad_diag_fractura: null,
      fecha_primer_diag_fractura: null,
      fecha_ultimo_diag_fractura: null,
      cantidad_diagnosticos: 1,
      codigo_diagnostico_1: '2123',
      fecha_creacion_diag_1: 1693267200000,
      mediana_mono_diag_1: 268.4,
      mediana_poli_diag_1: 219.2857142857,
      std_diag_1: 283.1971388352,
      prop_ctp_diag_1: 0.9036144578,
      q20_diag_1: 22,
      q80_diag_1: 371,
      lateralidad_diag_1: 'no especificada',
      ubicacion_lesion_diag_1: 'cabeza',
      cie10_diag_1: 'F920',
      bloque_general_diag_1: 'SALUD MENTAL',
      bloque_especifico_diag_1: 'TRASTORNOS MIXTOS DE LA CONDUCTA Y DE LAS EMOCIONES',
      codigo_grupo_diag_1: 'F92',
      cie10_grupo_diag_1: 'F00_F99',
      cie10_macro_diag_1: 'F00_F99',
      codigo_diagnostico_2: null,
      fecha_creacion_diag_2: null,
      mediana_mono_diag_2: null,
      mediana_poli_diag_2: null,
      std_diag_2: null,
      prop_ctp_diag_2: null,
      q20_diag_2: null,
      q80_diag_2: null,
      lateralidad_diag_2: null,
      ubicacion_lesion_diag_2: null,
      cie10_diag_2: null,
      bloque_general_diag_2: null,
      bloque_especifico_diag_2: null,
      codigo_grupo_diag_2: null,
      cie10_grupo_diag_2: null,
      cie10_macro_diag_2: null,
      dia_semana_principal: 'Martes',
      fecha_nacimiento_bp: 559785600000,
      sexo: 'femenino',
      dias_reposo_totales: 150,
      primer_fecha_inicio_reposo: 1684713600000,
      primer_fecha_indicacion_reposo: 1693267200000,
      dias_reposo_iniciales: 20,
      grado_total_incapacidad: null,
      fecha_resolucion: null,
      modalidad_incapacidad_desc: null,
      primera_terapia_fisica: null,
      primera_terapia_ocupacional: null,
      id_via_administracion: null,
      via_maxima: null,
      descripcion_formato: null,
      antibioticos: null,
      anticoagulantes_orales: null,
      hipoglicemiantes: null,
      tromboliticos: null,
      nivel_carga_laboral: 3,
      hospitalizado: null,
      anamnesis: 'EP salud mental en estudioactualmente con reposo tipo 1 indicado por m00e9dico externose acab00f3 su licencia el d00eda 18.9.23se realiza ingreso m00e9dico (listo)ingreso  psicolog00eda (listo)EPT tambi00e9n est00e1 listaacude para ingreso (abreviado) por ley 19.394Trabaja como educadora de p00e1rvulo, lleva 8 a00f1os en JUNJIRefiere s00edntomas de 1 a00f1o, asume que es porque trabaja en nivel con falta de personal.Por este motivo ha presentado sintomatolog00eda ansiosa, por cambios frecuentes en su trabajo, sobrecarga laboral.Estr00e9s asociado, crisis de angustia, ca00edda de pelo, urticaria, Refiere que se llevaba mucho trabajo a su casa.Al volver al trabajo en marzo 2023 present00f3 pesadillas, insomnio.Adem00e1s este a00f1o se asocia mala relaci00f3n con su jefatura Mar00eda Pilar Gonzalez, con trato deferente respecto a otras colegas.Se siente hostigada por esta persona, con actitudes de sospecha hacia ella. Relata Situaciones de convivencia en su trabajo en donde han reconocido a todas sus compa00f1eras menos a ella.Por este motivo ha consultado con m00e9dico particularque indic00f3 reposo com00fan, las que han sido rechazadas.Consulta desde marzo 2023 con m00e9dica particular Dra Rodriguez que indica tratamiento m00e9dico y reposo.Refiere licencias m00e9dicas rechazadas desde mayo 2023, por lo que tuvo que apelar a COMPIN y COLMENA.Derivada por esto, desde su isapre por ley 19.394ENTERADO DEL CASO.PACIENTE ACUDE A CONTROL ESPONTANEO POR ESTUDIO DE ENFERMEDAD PROFESIONAL DE SALUD MENTAL DEBIDO A QUE SE LE ACABA LICENCIA TIPO 1 EL DIA 18.09.23 POR LO QUE SOLICITA EXTENDER LICENCIA TIPO 6 DESDE HOY POR SOBRE LICENCIA TIPO 1 YA EN CURSO, DEBIDO A QUE NO QUIERE VOLVER A TRABAJAR DEVUELTA DEL 18 DE SEPTIEMBRE.',
      examen_fisico: 'gaf 55-65% duerme mal, pesadillas duerme de corrido 2 hrs y se despierta alt. del apetito, esta comiendo muchopesa 81kg (refiere ni siquiera en embarazo peso tanto) crisis de angustia: diarias la ultima crisis fue anoche, uso zubam odt 10mg CRISIS DE PANICO, CAIDA DE PELO, URTICARIA,gaf 5 ANIMO: EUTIMICA, SIN NERVIOSISMO, SIN LABILIDAD EMOCIONAL. SUEÑO: SIN ALTERACION. SIN IDEACION NI PLANEACION SUICIDA. GAF: 88%',
      indicacion_medico: 'Reposo si, con incapacidad laboral temporal con alta diferida ( 00daltimo d00eda de reposo el 30.09.2023  )Transporte: No. -.- MELATONINA 3 MG (A), ORAL, 3MG, C/24 HRS PM ,por 20  d00edas [ 0  ]Sin reposo, sin incapacidad temporal, alta inmediataTransporte: No.***ORDENES CLINICAS GENERADAS***EVALUACION PUESTO DE TRABAJO | ept salud mentalEVALUACION PUESTO DE TRABAJOEVALUACION PUESTO DE TRABAJOSin reposo, sin incapacidad temporal, alta inmediataTransporte: No.',
      cantidad_prestaciones_eco: null,
      primera_prestaciones_eco: null,
      ultima_prestaciones_eco: null,
      dif_entre_eco: null,
      dif_a_primer_eco: null,
      prop_eco_por_dias: null,
      cantidad_prestaciones_rm: null,
      primera_prestaciones_rm: null,
      ultima_prestaciones_rm: null,
      dif_entre_rm: null,
      dif_a_primer_rm: null,
      prop_rm_por_dias: null,
      cantidad_prestaciones_rx: null,
      primera_prestaciones_rx: null,
      ultima_prestaciones_rx: null,
      dif_entre_rx: null,
      dif_a_primer_rx: null,
      prop_rx_por_dias: null,
      cantidad_prestaciones_tac: null,
      primera_prestaciones_tac: null,
      ultima_prestaciones_tac: null,
      dif_entre_tac: null,
      dif_a_primer_tac: null,
      prop_tac_por_dias: null,
      cantidad_prestaciones_tmt: null,
      primera_prestaciones_tmt: null,
      ultima_prestaciones_tmt: null,
      dif_entre_tmt: null,
      dif_a_primer_tmt: null,
      prop_tmt_por_dias: null,
      cantidad_ordenes_cirugia: null,
      primera_orden_cirugia: null,
      ultima_orden_cirugia: null,
      dif_entre_cirugia: null,
      dif_a_primer_cirugia: null,
      prop_cirugia_por_dias: null,
      cantidad_ordenes_tf: null,
      primera_orden_tf: null,
      ultima_orden_tf: null,
      dif_entre_tf: null,
      dif_a_primer_tf: null,
      prop_tf_por_dias: null,
      dia_de_presentacion: 1,
      mes_de_presentacion: 8,
      es_hombre: 0,
      edad_presentacion: 35.9186020247,
      tuvo_tf: 0,
      tuvo_to: 0,
      dif_dias_a_tf: null,
      dif_dias_a_to: null,
      dif_dias_a_accidente: null,
      dif_dias_a_diag_1: 0,
      fecha_carga: '2023-10-09',
      hora_carga: '15:40',
      Max_protocolo: 165
    },
    '4': {
      puesto_trabajo: 'aseadora',
      fecha_accidente: 1693353600000,
      ingreso_tardio: null,
      mecanismo: '92',
      rubro: 612,
      cantidad_siniestros: 1,
      uo_sede_ingreso: 'HOSPITAL DEL TRABAJADOR',
      uo_servicio_ingreso: 'US_ATENCION_URGENCIA',
      uo_medica_ingreso: 'UM_URGENCIA',
      id_uo_tratamiento_ingreso: 'HTTURG',
      uo_tratamiento_ingreso: 'URGENCIA',
      tipo_siniestro_origen: '2',
      ult_tipo_siniestro_primer_dia: '2',
      tipo_siniestro_actual: '2',
      tipo_siniestro_origen_desc: 'Trayecto',
      ult_tipo_siniestro_primer_dia_desc: 'Trayecto',
      tipo_siniestro_actual_desc: 'Trayecto',
      tipo_ley: '1',
      tipo_ley_desc: 'Ley 16.744',
      anteced: 'AL MOMENTO DEL ACCIDENTE ESTABA EN DIRECCION A SU TRABAJO',
      relato_admision: 'AL MOMENTO DEL ACCIDENTE ESTABA EN DIRECCION A SU TRABAJO . LO QUE OCURRIO FUE QUE PACIENTE REFIERE QUE EN EL TRAYECTO A SU TRABAJO POR DESNIVEL EN EL PISO PACIENTE SUFRE CAIDA LESIONANDO EL TOBILLO IZQUIERDO Y RODILLA DERECHA. PACIENTE LLEGA AL TRABAJO Y DA AVISO A AL EMPRESA Y LA ENVIAN A URGENCIAS. EL ACCIDENTE OCURRIO CON CAIDA ., NO TIENE TESTIGOS DE SU ACCIDENTE, AVISO A LA EMPRESA, EL NOMBRE Y CARGO DE LA PERSONA ES VERONICA MENA , JEFATURA, FECHA Y HORA EN QUE AVISO A SU EMPRESA SOBRE EL ACCIDENTE: 30.08.2023 A LAS 07:20:00',
      cod_ubic_les: '900',
      parte_lesionada: 'Otras partes del cuerpo lesionadas',
      criterio_gravedad: '1',
      tiene_salud_mental: 0,
      tiene_fractura: 1,
      cantidad_diag_fractura: 1,
      fecha_primer_diag_fractura: 1694131200000,
      fecha_ultimo_diag_fractura: 1694131200000,
      cantidad_diagnosticos: 2,
      codigo_diagnostico_1: '8593',
      fecha_creacion_diag_1: 1694131200000,
      mediana_mono_diag_1: 137.8813953488,
      mediana_poli_diag_1: 243.0513833992,
      std_diag_1: 263.2379969429,
      prop_ctp_diag_1: 0.9690301548,
      q20_diag_1: 63,
      q80_diag_1: 253,
      lateralidad_diag_1: 'izquierda',
      ubicacion_lesion_diag_1: 'extremidad inferior',
      cie10_diag_1: 'S828',
      bloque_general_diag_1: 'EXTREMIDAD INFERIOR',
      bloque_especifico_diag_1: 'FRACTURA PIERNA, INCLUSIVE EL TOBILLO',
      codigo_grupo_diag_1: 'S82',
      cie10_grupo_diag_1: 'S00_T99',
      cie10_macro_diag_1: 'S',
      codigo_diagnostico_2: '8566',
      fecha_creacion_diag_2: 1693353600000,
      mediana_mono_diag_2: 4.2438070404,
      mediana_poli_diag_2: 14.4599247972,
      std_diag_2: 32.9301671828,
      prop_ctp_diag_2: 0.2477340253,
      q20_diag_2: 0,
      q80_diag_2: 1,
      lateralidad_diag_2: 'derecho',
      ubicacion_lesion_diag_2: 'extremidad inferior',
      cie10_diag_2: 'S801',
      bloque_general_diag_2: 'EXTREMIDAD INFERIOR',
      bloque_especifico_diag_2: 'TRAUMATISMO SUPERFICIAL DE LA PIERNA',
      codigo_grupo_diag_2: 'S80',
      cie10_grupo_diag_2: 'S00_T99',
      cie10_macro_diag_2: 'S',
      dia_semana_principal: 'Miercoles',
      fecha_nacimiento_bp: -388886400000,
      sexo: 'femenino',
      dias_reposo_totales: 41,
      primer_fecha_inicio_reposo: 1693353600000,
      primer_fecha_indicacion_reposo: 1693353600000,
      dias_reposo_iniciales: 41,
      grado_total_incapacidad: null,
      fecha_resolucion: null,
      modalidad_incapacidad_desc: null,
      primera_terapia_fisica: null,
      primera_terapia_ocupacional: null,
      id_via_administracion: null,
      via_maxima: null,
      descripcion_formato: null,
      antibioticos: null,
      anticoagulantes_orales: null,
      hipoglicemiantes: null,
      tromboliticos: null,
      nivel_carga_laboral: null,
      hospitalizado: null,
      anamnesis: 'TMT Policlinico Dr. contreras66 a00f1osAM DM2 (Metformina 1-0-0) HTA (Losartan 1-0-1) Hiportiroidismo (50mcg 1-0-1)Alergias -TBQ -OH -Drogas -Trabaja en aseoFA: 30.08.23Mecanismo: Torsion tobillo izquierdoDg: Fractura de chaput tobillo izquierod (Esguince moderado)2 semanas de evolucion.Ingresa en silla de uredas con bota y 2 bastones.Se evalua radiografias y TAC, se evidencia fragmento de Tilleaux-chaput minimo, sin otros rasgos evidentes de tibia o perone.Ex. Fisico:Pie con AVO difuso, mayor en maleolo medial, sin empastamiento. Dolor a la palpacion de maleolo lat, sin dolor en medial ni base del 500b0,AVO en dorso de pie dolor leve a la palpacion. Sin equimosis.Squeeze (-) chopart (-) Lisfranc (-).Plan: Caso discutido con Dr. Bazan Fellow TMT TyP, de manejo ortopedico con indicacion de carga a tolerancia y destete progresivo de bota y bastones, se indica Tf para eso. control en 4 semanas para evaluacion clinica.ReposoMedicamentos segun prescripcionFrio local 10 min 3 veces al dia por 3-5 diasMantener pie en alto durante reposoCaminar con bota y 2 batones carga a toleranciaTF para Educacion en marcha, ROM tobillo, propiocepcion, balance y fortalecimiento de peroneos, favor progresar en amrcha hacia destete de bastones y bota.Coontrol TMT Polibecado Contreras en 4 semanas para evaluacion clinica.Control SOSTransporte llevar y traer furgon.65 a00f1os, Auxiliar de aseo- AM: DM2, HTA- Alergia: niega- Fco: MTF, LST- AQ: niegaFA: 30/08/2023 07:08  Trayecto al trabajo, paciente sufre inversi00f3n de tobillo izquierdo al pisar desnivel, evoluciona con aumento de volumen asociado a limitaci00f3n funcional y dolor a la marcha. Al presentar inversi00f3n de tobillo paciente cae hacia su costado derecho golpe00e1ndose en rodilla derecha, en la cual no presenta molestias.Control medico Tomo conocimiento del caso FA: 30/08/2023DX: FX Bimaleolar CerradaTTO: Tramadol/Paracetamol / Celecoxib / Clexane Buena adherencia, buena tolerancia, niega RAMsNiega epistaxis, hematuria, melena, gingivorragia Refiere dolor ++/+++ a nivel de extremidad, inflamaci00f3nAcude con Bota W y dos bastones, ingresando a box con silla de ruedas Desde el ingreso reportan: Control con T&P en una semana y Rx con carga comparativa Paciente al momento de la evaluaci00f3n, no tolera la carga Control medico con especialista 15/089/2023',
      examen_fisico: 'TOBILLO Y PIE IZQUIERDO  AVO ++/+++ en cara lateral de tobillo a nivel de maleolo fibular sensible a la palpacion, dolor en LTFA y LCF. sin dolor en ligamento deltoide. Squeeze negativo. Cajon negativo. NV indemne. Sin dolor en base de 5to MTT. Sin dolor en Lisfranc ni Chopart. Marcha con moderada claudicacion. RODILLA DERECHA  Sin AVO, sin equimosis, leve dolor en cara anterolateral de rodilla. ROM sin limitacion. Sin signo de inestabilidad de rodilla. Sin claudicacion. NV indemne.BCGHemodinamicamente estableAcude caminando con apoyo ortesico, dos bastones y bota Pie izquierdo: AVO ++/+++ sin hematoma o lesiones en piel, dolor palpatorio a nivel de borde lateral de tobillo, squeeze negativo, no logra carga, maniobras de bostezo no exploradas por dolor. SNC: conservado  ',
      indicacion_medico: 'Reposo si, con incapacidad laboral temporalTransporte si, Llevar-Traer en Furg00f3n , hasta el pr00f3ximo control200b***ORDENES CLINICAS GENERADAS*** -.- ENOXAPARINA 40 MG / 0,4 ML (A), SUBCUTANEA, 40MG, C/24 HRS AM ,por 30  d00edas [ 0  ]TRAMADOL 37.5 MG - PARACETAMOL 325 MG (A), ORAL, 1CMP, C/8 HRS ,por 21  d00edas [ 0  ]ACIDO ASCORBICO 1 GR  EFERVESCENTE (A), ORAL, 1G, C/24 HRS AM ,por 45  d00edas [ 0  ]Reposo si, con incapacidad laboral temporalTransporte si, Llevar-Traer en Furg00f3n , hasta el pr00f3ximo control200b***ORDENES CLINICAS GENERADAS***RX TOBILLO PROYECCION CON CARGA | Bilatera | Fractura de mal00e9olo tibial. Rx con carga comparatiRX TOBILLO PROYECCION CON CARGAReposo si, con incapacidad laboral temporalTransporte si, Llevar-Traer en Furg00f3n , hasta el pr00f3ximo control200b -.- TRAMADOL 37.5 MG - PARACETAMOL 325 MG (A), ORAL, 1CMP, C/8 HRS ,por 8  d00edas [ 0  ]CELECOXIB 200 MG (A), ORAL, 200MG, C/24 HRS AM ,por 8  d00edas [ 0  ]',
      cantidad_prestaciones_eco: null,
      primera_prestaciones_eco: null,
      ultima_prestaciones_eco: null,
      dif_entre_eco: null,
      dif_a_primer_eco: null,
      prop_eco_por_dias: null,
      cantidad_prestaciones_rm: null,
      primera_prestaciones_rm: null,
      ultima_prestaciones_rm: null,
      dif_entre_rm: null,
      dif_a_primer_rm: null,
      prop_rm_por_dias: null,
      cantidad_prestaciones_rx: 3,
      primera_prestaciones_rx: 1693353600000,
      ultima_prestaciones_rx: 1694131200000,
      dif_entre_rx: 10,
      dif_a_primer_rx: 0,
      prop_rx_por_dias: 1.3333333731,
      cantidad_prestaciones_tac: 1,
      primera_prestaciones_tac: 1693353600000,
      ultima_prestaciones_tac: 1693353600000,
      dif_entre_tac: 1,
      dif_a_primer_tac: 0,
      prop_tac_por_dias: null,
      cantidad_prestaciones_tmt: 5,
      primera_prestaciones_tmt: 1693353600000,
      ultima_prestaciones_tmt: 1697155200000,
      dif_entre_tmt: 45,
      dif_a_primer_tmt: 0,
      prop_tmt_por_dias: 1.1136363745,
      cantidad_ordenes_cirugia: null,
      primera_orden_cirugia: null,
      ultima_orden_cirugia: null,
      dif_entre_cirugia: null,
      dif_a_primer_cirugia: null,
      prop_cirugia_por_dias: null,
      cantidad_ordenes_tf: 2,
      primera_orden_tf: 1694736000000,
      ultima_orden_tf: 1695686400000,
      dif_entre_tf: 12,
      dif_a_primer_tf: -11,
      prop_tf_por_dias: 1.1818181276,
      dia_de_presentacion: 2,
      mes_de_presentacion: 8,
      es_hombre: 0,
      edad_presentacion: 65.9835588684,
      tuvo_tf: 0,
      tuvo_to: 0,
      dif_dias_a_tf: null,
      dif_dias_a_to: null,
      dif_dias_a_accidente: 0,
      dif_dias_a_diag_1: 9,
      fecha_carga: '2023-10-09',
      hora_carga: '15:40',
      Max_protocolo: 120
    },
    '5': {
      puesto_trabajo: 'docente',
      fecha_accidente: null,
      ingreso_tardio: null,
      mecanismo: null,
      rubro: 810,
      cantidad_siniestros: 1,
      uo_sede_ingreso: ' TELEMEDICINA',
      uo_servicio_ingreso: 'US_ATENCION_AMBULATORIA',
      uo_medica_ingreso: 'OTRA',
      id_uo_tratamiento_ingreso: 'TELEMAPR',
      uo_tratamiento_ingreso: 'CONSULTA_AP',
      tipo_siniestro_origen: '3',
      ult_tipo_siniestro_primer_dia: '3',
      tipo_siniestro_actual: '3',
      tipo_siniestro_origen_desc: 'Enfermedad Profesional',
      ult_tipo_siniestro_primer_dia_desc: 'Enfermedad Profesional',
      tipo_siniestro_actual_desc: 'Enfermedad Profesional',
      tipo_ley: '1',
      tipo_ley_desc: 'Ley 16.744',
      anteced: 'mal dormir ,sensacion de acoso',
      relato_admision: null,
      cod_ubic_les: '900',
      parte_lesionada: 'Otras partes del cuerpo lesionadas',
      criterio_gravedad: null,
      tiene_salud_mental: 1,
      tiene_fractura: 0,
      cantidad_diag_fractura: null,
      fecha_primer_diag_fractura: null,
      fecha_ultimo_diag_fractura: null,
      cantidad_diagnosticos: 1,
      codigo_diagnostico_1: '1982',
      fecha_creacion_diag_1: 1693440000000,
      mediana_mono_diag_1: 41.4529214738,
      mediana_poli_diag_1: 99.5868895019,
      std_diag_1: 181.1986862291,
      prop_ctp_diag_1: 0.7362851674,
      q20_diag_1: 0,
      q80_diag_1: 42,
      lateralidad_diag_1: 'no especificada',
      ubicacion_lesion_diag_1: 'cabeza',
      cie10_diag_1: 'F432',
      bloque_general_diag_1: 'SALUD MENTAL',
      bloque_especifico_diag_1: 'REACCION AL ESTRES GRAVE Y TRASTORNOS DE ADAPTACION',
      codigo_grupo_diag_1: 'F43',
      cie10_grupo_diag_1: 'F00_F99',
      cie10_macro_diag_1: 'F00_F99',
      codigo_diagnostico_2: null,
      fecha_creacion_diag_2: null,
      mediana_mono_diag_2: null,
      mediana_poli_diag_2: null,
      std_diag_2: null,
      prop_ctp_diag_2: null,
      q20_diag_2: null,
      q80_diag_2: null,
      lateralidad_diag_2: null,
      ubicacion_lesion_diag_2: null,
      cie10_diag_2: null,
      bloque_general_diag_2: null,
      bloque_especifico_diag_2: null,
      codigo_grupo_diag_2: null,
      cie10_grupo_diag_2: null,
      cie10_macro_diag_2: null,
      dia_semana_principal: 'Jueves',
      fecha_nacimiento_bp: 369446400000,
      sexo: 'femenino',
      dias_reposo_totales: 12,
      primer_fecha_inicio_reposo: 1693440000000,
      primer_fecha_indicacion_reposo: 1693440000000,
      dias_reposo_iniciales: 0,
      grado_total_incapacidad: null,
      fecha_resolucion: null,
      modalidad_incapacidad_desc: null,
      primera_terapia_fisica: null,
      primera_terapia_ocupacional: null,
      id_via_administracion: null,
      via_maxima: null,
      descripcion_formato: null,
      antibioticos: null,
      anticoagulantes_orales: null,
      hipoglicemiantes: null,
      tromboliticos: null,
      nivel_carga_laboral: null,
      hospitalizado: null,
      anamnesis: 'paciente se acoge como patologia laboral. indicaciones reposo laboral valoracion siquiatria 19 10 2023 valoracion sicologo quincenal control 20  10 2023 paciente evaluada por comite de calificacion . el cual determina que es una patologia profesional de origen laboral indicaciones reposo laboral valoracion siquiatria valoracion sicologo  control medico 15 dias dr fuentes',
      examen_fisico: 'paciente se acoge como patologia laboralrindicaciones rreposo laboralrvaloracion siquiatria 19 10 2023rvaloracion sicologo quincenalrcontrol 20  10 2023paciente evaluada por comite de calificacion . el cualr determina que es una patologia profesional de origen laboralrindicaciones rreposo laboralrvaloracion siquiatriarvaloracion sicologo rcontrol medico 15 dias rdr fuentes',
      indicacion_medico: 'rindicaciones rreposo laboralrvaloracion siquiatria 19 10 2023rvaloracion sicologo quincenalrcontrol 20  10 2023reposo laboralrvaloracion siquiatriarvaloracion sicologo rcontrol medico 15 dias rdr fuentes',
      cantidad_prestaciones_eco: null,
      primera_prestaciones_eco: null,
      ultima_prestaciones_eco: null,
      dif_entre_eco: null,
      dif_a_primer_eco: null,
      prop_eco_por_dias: null,
      cantidad_prestaciones_rm: null,
      primera_prestaciones_rm: null,
      ultima_prestaciones_rm: null,
      dif_entre_rm: null,
      dif_a_primer_rm: null,
      prop_rm_por_dias: null,
      cantidad_prestaciones_rx: null,
      primera_prestaciones_rx: null,
      ultima_prestaciones_rx: null,
      dif_entre_rx: null,
      dif_a_primer_rx: null,
      prop_rx_por_dias: null,
      cantidad_prestaciones_tac: null,
      primera_prestaciones_tac: null,
      ultima_prestaciones_tac: null,
      dif_entre_tac: null,
      dif_a_primer_tac: null,
      prop_tac_por_dias: null,
      cantidad_prestaciones_tmt: null,
      primera_prestaciones_tmt: null,
      ultima_prestaciones_tmt: null,
      dif_entre_tmt: null,
      dif_a_primer_tmt: null,
      prop_tmt_por_dias: null,
      cantidad_ordenes_cirugia: null,
      primera_orden_cirugia: null,
      ultima_orden_cirugia: null,
      dif_entre_cirugia: null,
      dif_a_primer_cirugia: null,
      prop_cirugia_por_dias: null,
      cantidad_ordenes_tf: null,
      primera_orden_tf: null,
      ultima_orden_tf: null,
      dif_entre_tf: null,
      dif_a_primer_tf: null,
      prop_tf_por_dias: null,
      dia_de_presentacion: 3,
      mes_de_presentacion: 8,
      es_hombre: 0,
      edad_presentacion: 41.9556869751,
      tuvo_tf: 0,
      tuvo_to: 0,
      dif_dias_a_tf: null,
      dif_dias_a_to: null,
      dif_dias_a_accidente: null,
      dif_dias_a_diag_1: 0,
      fecha_carga: '2023-10-09',
      hora_carga: '15:40',
      Max_protocolo: 30
    }
  }

function calcularFunction() {
    let resultadoCard = document.getElementById('resultadoCard')
    let prediccion = document.getElementById('prediccion')
    const btnCase = document.getElementById('SelectCaseNumber')

    if (btnCase.innerText == 'Seleccionar caso'){
        alert('Seleccione un caso para poder predecir')
    }
    else {
        prediccion.innerHTML = data[caseNumber].Max_protocolo
        resultadoCard.style.display = 'block'
    }
}

function resetClick() {
    let tabla = document.getElementById('tablaVariables');
    let resultadoCard = document.getElementById('resultadoCard')
    let input = document.getElementsByClassName('form-control');
    const btnCase = document.getElementById('SelectCaseNumber')
    
    for (let i = 0; i < input.length; i++){
        input[i].value = '';
    }
    textoClinico.value = ''

    tabla.style.display = 'none'
    resultadoCard.style.display = 'none'
    btnCase.innerHTML = 'Seleccionar caso'

}

function showVarClick() {
    let tabla = document.getElementById('tablaVariables')
    tabla.style.display = 'block'
}

function selectCase(element) {
    const id = parseInt(element.id)
    const btnCase = document.getElementById('SelectCaseNumber')

    btnCase.innerText = 'Caso '+(id+1)+' '

    caseNumber = id
    varInput1.value = data[id].bloque_especifico_diag_1
    varInput2.value = data[id].sexo
    varInput3.value = data[id].tipo_siniestro_origen_desc
    varInput4.value = data[id].nivel_carga_laboral
    varInput5.value = data[id].dia_semana_principal
    textoClinico.value = data[id].examen_fisico
}

function alertNoCase() {
    
}




